language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm
install: 
    - composer install
    - composer dumpautoload
script:
    - phpunit --bootstrap=./vendor/autoload.php ./tests